### ISSUE TITLE
document how auth works

### ISSUE THREAD

**Issue by Dieterbe** [raintank/tsdb-gw#195]
instance auth, single tenant, multi tenant, etc
org vs tenant, etc
involvement of grafana.com (how it maps to those datatypes)
bearer tokens vs api key vs basic auth that has "api_key" as password, etc

**Comment by DanCech** [comment]
documenting would be a good start.  The way the auth code is implemented right now it's quite difficult to follow what's going on with the multiple packages and errors being repackaged, etc.  In my opinion it would be a good idea to refactor things and try to make it simpler and easier to read (and audit).

It may be helpful for us to provide a dedicated endpoint on grafana.com to be used by the per-instance auth instead of needing to make 2 calls, that shouldn't be too difficult to add if it would help simplify things.

**Comment by Dieterbe** [comment]
* auth has been documented in our internal docs
* I agree the auth code could use a refactor
* re changing grafana.com api, no idea.
