### ISSUE TITLE
built-in auth = fragile ingestion?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/tsdb-gw#9]
@nopzor1200 brought up a good point: having tsdb-gw rely on external services (besides kafka) makes it fragile in the ingestion path.
AFAIK the only external service is grafana.net (correct me if i'm wrong) and we cache authentication for 5min. but still, if gnet goes down for >5min it means we can't authenticate and ingestion breaks.

an alternative design is put as little between user and kafka as possible (basically take auth of tsdb-gw ingest path), and have something else consume from kafka, do auth, set org-id, publish new data into kafka in a different topic.

or.. maybe support indefinite caching in case gnet goes down. if gnet is down people can't create new api keys anyway, so the indefinitely-cached auth data will be stale but it'll still be up to date.
but we shouldn't use the indefinite cached data in the case gnet is up of course, in case keys get revoked etc.

**Comment by DanCech** [comment]
I'd agree that infinite lifetime cache in the case of a grafana.net timeout is the simplest solution.  You might want to also have a flag that's set when a timeout occurs so that it can serve directly from cache for the next X seconds after a timeout rather than having to time out on every request that hits an "expired" cache key.

**Comment by woodsaj** [comment]
fixed in https://github.com/raintank/raintank-apps/commit/8738d0e2a359ac01676b1b80ab3303e3aac9ee9a
